### ISSUE TITLE
yarn example fails with semantic error TS2339

### ISSUE THREAD

**Issue by dlee** [boardgameio/boardgame.io#1204]
```
❯ yarn examples
yarn run v1.22.22
$ npm run start

> boardgame.io@0.50.2 prestart
> run-p examples:install build


> boardgame.io@0.50.2 examples:install
> node scripts/install-examples.js


> boardgame.io@0.50.2 build
> cross-env BABEL_ENV=rollup rollup --config rollup.config.js  --silent

Starting the application...
[!] (plugin rpt2) Error: /Users/dlee/code/boardgame.io/src/server/transport/socketio.ts(167,17): semantic error TS2339: Property 'io' does not exist on type 'BaseContext & DefaultContext & { db: Async | Sync; auth: Auth; }'.
src/server/transport/socketio.ts
Error: /Users/dlee/code/boardgame.io/src/server/transport/socketio.ts(167,17): semantic error TS2339: Property 'io' does not exist on type 'BaseContext & DefaultContext & { db: Async | Sync; auth: Auth; }'.
    at error (/Users/dlee/code/boardgame.io/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at throwPluginError (/Users/dlee/code/boardgame.io/node_modules/rollup/dist/shared/node-entry.js:11878:12)
    at Object.error (/Users/dlee/code/boardgame.io/node_modules/rollup/dist/shared/node-entry.js:12912:24)
    at Object.error (/Users/dlee/code/boardgame.io/node_modules/rollup/dist/shared/node-entry.js:12081:38)
    at RollupContext.error (/Users/dlee/code/boardgame.io/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at /Users/dlee/code/boardgame.io/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
    at arrayEach (/Users/dlee/code/boardgame.io/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at _.each (/Users/dlee/code/boardgame.io/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9342:14)
    at printDiagnostics (/Users/dlee/code/boardgame.io/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/Users/dlee/code/boardgame.io/node_modules/rollup-plugin-typescript2/src/index.ts:225:5)
    at /Users/dlee/code/boardgame.io/node_modules/rollup/dist/shared/node-entry.js:13117:25

ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Rupesh-ark** [comment]
This no longer reproduces on main — the type error in `src/server/transport/socketio.ts` is gone after the toolchain modernization and `tsc --noEmit` is clean. Remaining example type fixes are being handled in #1224. Closing; please reopen if a fresh clone of main still fails for you.
