### ISSUE TITLE
Unable to install module from Github repo

### ISSUE THREAD

**Issue by musashidev** [boardgameio/boardgame.io#837]
Hello, I am unable to install from npm pointing to this repo instead of `npm install boardgame.io`

```
npm install https://github.com/boardgameio/boardgame.io

> boardgame.io@0.41.1 prepack /home/*/.npm/_cacache/tmp/git-clone-73366522
> run-s build proxydirs


> boardgame.io@0.41.1 build /home/*/.npm/_cacache/tmp/git-clone-73366522
> cross-env BABEL_ENV=rollup rollup --config rollup.config.js  --silent

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn rollup ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boardgame.io@0.41.1 build: `cross-env BABEL_ENV=rollup rollup --config rollup.config.js  --silent`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the boardgame.io@0.41.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/*/.npm/_logs/2020-10-26T12_27_31_507Z-debug.log
ERROR: "build" exited with 1.
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/*/.npm/_logs/2020-10-26T12_27_31_548Z-debug.log

```

Any idea on how to fix it?

**Comment by musashidev** [comment]
I just saw this https://github.com/boardgameio/boardgame.io/pull/749
